### ISSUE TITLE
how to only download waybar .conf?

### ISSUE THREAD

**Issue by r0l1ka** [niksingh710/gdots#3]
i wanna download only waybar config to my dots, but i can't, it just dosn't work, it cant find colors.css

sorry if am stupid
and sorry dor my english
![image](https://github.com/user-attachments/assets/0068f2eb-db91-4d65-80ef-68affd573330)

**Comment by semi710** [comment]
`colors.css` is failing coz it get's generated by my pywal script.
i have a sample of colors.css [here](https://github.com/niksingh710/gdots/blob/master/extra/wal/colors-waybar.css) just download this file or copy the content of this file in the dir `~/.config/waybar/` with a file name `colors.css`.

update me it this works for you.

**Comment by r0l1ka** [comment]
thanks! it works!
